title: Laís Lavra # your name (or website title) here
logo: "/images/Image-github.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I am Laís Lavra, a high energy physicist from Brazil |:wave:| 
  <br><br>

  <a href="https://www.linkedin.com/in/laislavra">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


