title: Laís Soares Lavra # your name (or website title) here
logo: <img src="/images/Image-github.png" height="60" width="60">
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Hi, I am Laís, a high energy physicist from Brazil! 
  <br><br>

  <a href="https://www.linkedin.com/in/laislavra">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


