title: Laís Lavra # your name (or website title) here
logo: "/images/Image-github.png?raw=false" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I am Laís Lavra, a high energy physicist from Brazil, currently living in France. 
  <br><br>
  My research interests are flavour physics, particle tracking detectors and machine learning applications in particle physics.
  <br><br>
  <a href="https://www.linkedin.com/in/laislavra">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


