title: John Doe # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Laís Lavra and I am a high energy physicist. 
  I have a PhD in Particle Physics from <a href="https://www.gov.br/cbpf/pt-br">CBPF</a>, with research focused on studying 
  differences between matter and antimatter in particles containing beauty quarks with the <a href="https://lhcb-outreach.web.cern.ch/">LHCb experiment</a> at <a href="https://home.cern/">CERN</a> in Switzerland. 
  <br><br>
  I am also a former Postdoctoral Fellow at <a href="https://www.cnrs.fr/">CNRS</a>, in France, where my work focused on 
  searching for rare decays and commissioning the new scintillating fibre tracker for the LHCb experiment.  
  <br><br>
  <a href="https://www.linkedin.com/in/laislavra">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


